import OpenAI from "openai";
import { CategoryScore, Finding } from "../types";

const VISION_PROMPT = `You are an expert web designer with impeccable taste and 20 years of experience. You've seen thousands of websites and can instantly tell when one was generated by AI (v0, Bolt, Lovable, Cursor, etc.) vs. hand-crafted by a skilled designer.

Analyze this website screenshot and evaluate how much it looks like generic AI-generated "slop" design. 

Score EACH category from 0-100 where:
- 0 = Completely original, clearly hand-crafted
- 50 = Could go either way, some generic elements
- 100 = Maximum AI slop, completely generic

Categories to score:

1. **visual_design** (0-100): Color palette originality, use of whitespace, visual personality, brand distinction. AI slop tells: purple/indigo gradients, generic blue, oversized hero sections with gradient backgrounds, excessive drop shadows.

2. **layout_originality** (0-100): Page structure, section arrangement, grid usage. AI slop tells: Hero > 3-col features > pricing > testimonials > FAQ > CTA, everything centered, cookie-cutter card grids.

3. **imagery** (0-100): Quality and originality of images, icons, illustrations. AI slop tells: generic stock photos, AI-generated hero images, Lucide/Heroicon defaults, abstract blob backgrounds, AI-generated headshots in testimonials.

For EACH category, also provide 1-2 specific observations about what you see.

Return ONLY valid JSON in this exact format:
{
  "visual_design": { "score": <number>, "observations": ["<string>", "<string>"] },
  "layout_originality": { "score": <number>, "observations": ["<string>", "<string>"] },
  "imagery": { "score": <number>, "observations": ["<string>", "<string>"] }
}`;

interface VisionResult {
  visual_design: { score: number; observations: string[] };
  layout_originality: { score: number; observations: string[] };
  imagery: { score: number; observations: string[] };
}

export async function analyzeVision(
  screenshotBase64: string
): Promise<{
  visual: Partial<CategoryScore>;
  layout: Partial<CategoryScore>;
  imagery: CategoryScore;
}> {
  const apiKey = process.env.MOONSHOT_API_KEY || process.env.KIMI_API_KEY;

  if (!apiKey) {
    // Return default scores when no API key is available
    console.warn("No MOONSHOT_API_KEY or KIMI_API_KEY found. Using heuristic-only scoring.");
    return {
      visual: { score: undefined, findings: [] },
      layout: { score: undefined, findings: [] },
      imagery: {
        score: 50, // neutral default
        weight: 0.15,
        findings: [
          {
            what: "Vision analysis unavailable",
            why: "No Kimi K2.5 API key configured — image analysis skipped",
            fix: "Set MOONSHOT_API_KEY environment variable to enable AI-powered visual analysis",
            severity: "low",
          },
        ],
      },
    };
  }

  try {
    const client = new OpenAI({
      apiKey,
      baseURL: "https://api.moonshot.cn/v1",
    });

    const response = await client.chat.completions.create({
      model: "kimi-k2.5",
      messages: [
        {
          role: "user",
          content: [
            { type: "text", text: VISION_PROMPT },
            {
              type: "image_url",
              image_url: {
                url: `data:image/jpeg;base64,${screenshotBase64}`,
              },
            },
          ],
        },
      ],
      max_tokens: 1000,
      temperature: 0.3,
    });

    const content = response.choices[0]?.message?.content || "{}";
    // Extract JSON from potential markdown code blocks
    const jsonMatch = content.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      throw new Error("No JSON found in vision response");
    }

    const result: VisionResult = JSON.parse(jsonMatch[0]);

    const visualFindings: Finding[] = (
      result.visual_design?.observations || []
    ).map((obs) => ({
      what: obs,
      why: "Identified by AI visual analysis",
      fix: "Consider making this element more unique and intentional",
      severity: (result.visual_design.score > 60 ? "high" : "medium") as Finding["severity"],
    }));

    const layoutFindings: Finding[] = (
      result.layout_originality?.observations || []
    ).map((obs) => ({
      what: obs,
      why: "Identified by AI layout analysis",
      fix: "Rethink this layout pattern for more originality",
      severity: (result.layout_originality.score > 60 ? "high" : "medium") as Finding["severity"],
    }));

    const imageryFindings: Finding[] = (
      result.imagery?.observations || []
    ).map((obs) => ({
      what: obs,
      why: "Identified by AI imagery analysis",
      fix: "Use original photography, custom illustrations, or carefully curated stock",
      severity: (result.imagery.score > 60 ? "high" : "medium") as Finding["severity"],
    }));

    return {
      visual: {
        score: clamp(result.visual_design?.score ?? 50),
        findings: visualFindings,
      },
      layout: {
        score: clamp(result.layout_originality?.score ?? 50),
        findings: layoutFindings,
      },
      imagery: {
        score: clamp(result.imagery?.score ?? 50),
        weight: 0.15,
        findings: imageryFindings.length
          ? imageryFindings
          : [
              {
                what: "Image analysis coming soon",
                why: "Full AI image detection (identifying AI-generated photos) is planned for v0.2",
                fix: "For now, make sure you're using real photography or clearly original illustrations",
                severity: "low",
              },
            ],
      },
    };
  } catch (error) {
    console.error("Vision analysis failed:", error);
    return {
      visual: { score: undefined, findings: [] },
      layout: { score: undefined, findings: [] },
      imagery: {
        score: 50,
        weight: 0.15,
        findings: [
          {
            what: "Vision analysis error",
            why: `Could not complete AI visual analysis: ${error instanceof Error ? error.message : "Unknown error"}`,
            fix: "This scan used heuristic-only analysis. Results may be less accurate",
            severity: "low",
          },
        ],
      },
    };
  }
}

function clamp(n: number): number {
  return Math.max(0, Math.min(100, Math.round(n)));
}
